### ISSUE TITLE
I type in a show, then it asks me the stuff and when I select an episode, this error comes up.

### ISSUE THREAD

**Issue by ninko76** [Soviena/kaa.si-cli#5]
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/kaasi", line 33, in <module>
    sys.exit(load_entry_point('kaasi-cli==1.0.9', 'console_scripts', 'kaasi')())
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/kaasi", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kaasi_cli-1.0.9-py3.10.egg/kaasi_cli/kaasi.py", line 410, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kaasi_cli-1.0.9-py3.10.egg/kaasi_cli/kaa.py", line 43, in select_episode
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kaasi_cli-1.0.9-py3.10.egg/kaasi_cli/kaa.py", line 10, in parse_appData
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by Soviena** [comment]
can i get detailed information like what anime on which episode ?
