### ISSUE TITLE
Doesn't work after entering episode number, IndexError.

### ISSUE THREAD

**Issue by saiprasadhakki** [Soviena/kaa.si-cli#7]
I have python and vlc in path and no anilist login.
The following is the block I got:

Traceback (most recent call last):
  File "C:\Program Files\Python311\Scripts\kaasi-script.py", line 33, in <module>
    sys.exit(load_entry_point('kaasi-cli==1.0.9', 'console_scripts', 'kaasi')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Scripts\kaasi-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\importlib\metadata\__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Program Files\Python311\Lib\site-packages\kaasi_cli-1.0.9-py3.11.egg\kaasi_cli\kaasi.py", line 418, in <module>
  File "C:\Program Files\Python311\Lib\site-packages\kaasi_cli-1.0.9-py3.11.egg\kaasi_cli\scraper.py", line 18, in vidstreaming
IndexError: list index out of range

**Comment by Soviena** [comment]
lookslike its try using the gogo server / vidstreaming. Currently vidstreaming / gogo is broken. can you tell me which anime causing this ?

**Comment by saiprasadhakki** [comment]
True vidstreaming has been down since yesterday, is there any way to change/select server? No Game, No Life is the anime. By the way great project keep up the good work!

**Comment by Soviena** [comment]
currently, the website kaasi is still using gogoanime server for old anime. so for now its not possible to change server for old anime. for newer anime from 2018 - now, there is pink-bird, maverickki server that will work.
